In [1]:
import pandas as pd
import numpy as np

import os

In [18]:
os.getcwd()

'G:\\Recommendation Engine\\Recommendation Systems\\13. Colloborative Filtering\\Case Study-Recommendation Engine for Ecommerce Company (Hitech)'

In [17]:
os.chdir(r"G:\Recommendation Engine\Recommendation Systems\13. Colloborative Filtering\Case Study-Recommendation Engine for Ecommerce Company (Hitech)")

### Reading Data

In [20]:
df=pd.read_csv("CF_Input5.csv")

In [21]:
df.head()

         user   item  rating
0  USER_00001  IT_01       5
1  USER_00001  IT_02       4
2  USER_00001  IT_03       5
3  USER_00001  IT_04       5
4  USER_00001  IT_06       3

### Creating an User - Item Metrics

In [25]:
user_item = df.pivot(index='user',columns='item',values='rating')

user_item.fillna(0,inplace=True)

In [27]:
user_item.shape

(10000, 15)

In [28]:
user_item

item,IT_01,IT_02,IT_03,IT_04,IT_05,IT_06,IT_07,IT_08,IT_09,IT_10,IT_11,IT_12,IT_13,IT_14,IT_15
user,,,,,,,,,,,,,,,
USER_00001,5.0,4.0,5.0,5.0,0.0,3.0,1.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0
USER_00002,0.0,0.0,0.0,0.0,2.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
USER_00003,0.0,0.0,5.0,4.0,0.0,1.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
USER_00004,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,5.0,1.0,0.0,4.0,0.0
USER_00005,0.0,5.0,0.0,5.0,0.0,3.0,0.0,0.0,4.0,0.0,4.0,0.0,5.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USER_09996,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0,0.0,2.0,5.0,0.0,0.0,0.0,0.0
USER_09997,3.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
USER_09998,0.0,4.0,0.0,0.0,4.0,0.0,4.0,0.0,4.0,0.0,3.0,0.0,5.0,0.0,5.0
USER_09999,0.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
USER_10000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,0.0,0.0,0.0,3.0,0.0

## Creating an Item User Metrics

In [29]:
item_user = df.pivot(index='item',columns='user',values='rating')

In [31]:
item_user.fillna(0,inplace=True)

In [32]:
item_user

user,USER_00001,USER_00002,USER_00003,USER_00004,USER_00005,USER_00006,USER_00007,USER_00008,USER_00009,USER_00010,...,USER_09991,USER_09992,USER_09993,USER_09994,USER_09995,USER_09996,USER_09997,USER_09998,USER_09999,USER_10000
item,,,,,,,,,,,,,,,,,,,,,
IT_01,5.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,3.0,1.0,0.0,3.0,0.0,0.0,0.0
IT_02,4.0,0.0,0.0,0.0,5.0,0.0,0.0,1.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0
IT_03,5.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0
IT_04,5.0,0.0,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IT_05,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,3.0,5.0,2.0,0.0,0.0,4.0,4.0,0.0,0.0
IT_06,3.0,3.0,1.0,0.0,3.0,0.0,2.0,5.0,5.0,5.0,...,0.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0
IT_07,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0
IT_08,0.0,3.0,2.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
IT_09,0.0,0.0,0.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,4.0,0.0,1.0
IT_10,0.0,0.0,1.0,4.0,0.0,2.0,0.0,0.0,0.0,1.0,...,0.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0,0.0,5.0
IT_11,4.0,0.0,0.0,5.0,4.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,3.0,0.0,0.0
IT_12,4.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IT_13,0.0,0.0,0.0,0.0,5.0,0.0,4.0,0.0,0.0,0.0,...,4.0,4.0,0.0,0.0,1.0,0.0,0.0,5.0,0.0,0.0
IT_14,0.0,0.0,0.0,4.0,0.0,0.0,2.0,5.0,0.0,4.0,...,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0
IT_15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0

### Finding Similarities

In [40]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

##### Finding Similar Users

In [34]:
username =item_user.columns

In [36]:
username

Index(['USER_00001', 'USER_00002', 'USER_00003', 'USER_00004', 'USER_00005',
       'USER_00006', 'USER_00007', 'USER_00008', 'USER_00009', 'USER_00010',
       ...
       'USER_09991', 'USER_09992', 'USER_09993', 'USER_09994', 'USER_09995',
       'USER_09996', 'USER_09997', 'USER_09998', 'USER_09999', 'USER_10000'],
      dtype='object', name='user', length=10000)

In [37]:
itemnames=user_item.columns

In [38]:
itemnames

Index(['IT_01', 'IT_02', 'IT_03', 'IT_04', 'IT_05', 'IT_06', 'IT_07', 'IT_08',
       'IT_09', 'IT_10', 'IT_11', 'IT_12', 'IT_13', 'IT_14', 'IT_15'],
      dtype='object', name='item')

In [43]:
user_sim = 1 - pairwise_distances(user_item,metric='cosine')

In [45]:
user_sim = pd.DataFrame(user_sim,index=username,columns=username)

In [46]:
user_sim

user,USER_00001,USER_00002,USER_00003,USER_00004,USER_00005,USER_00006,USER_00007,USER_00008,USER_00009,USER_00010,...,USER_09991,USER_09992,USER_09993,USER_09994,USER_09995,USER_09996,USER_09997,USER_09998,USER_09999,USER_10000
user,,,,,,,,,,,,,,,,,,,,,
USER_00001,1.000000,0.180805,0.607109,0.427024,0.563564,0.246977,0.106199,0.299209,0.338664,0.327833,...,0.287129,0.051016,0.366800,0.554605,0.176998,0.342196,0.330875,0.250191,0.105661,0.072259
USER_00002,0.180805,1.000000,0.273735,0.000000,0.174241,0.371192,0.255377,0.359755,0.678657,0.437968,...,0.000000,0.368037,0.226166,0.177822,0.000000,0.595880,0.205331,0.225613,0.254084,0.000000
USER_00003,0.607109,0.273735,1.000000,0.058640,0.311494,0.207732,0.059549,0.078645,0.094950,0.122551,...,0.386406,0.028606,0.537924,0.466478,0.119098,0.258046,0.000000,0.000000,0.025392,0.243108
USER_00004,0.427024,0.000000,0.058640,1.000000,0.335936,0.596380,0.164122,0.249265,0.196267,0.281467,...,0.212993,0.000000,0.359738,0.321412,0.533396,0.451335,0.432991,0.280926,0.279927,0.603023
USER_00005,0.563564,0.174241,0.311494,0.335936,1.000000,0.396684,0.492764,0.200240,0.181316,0.390038,...,0.553409,0.418805,0.201415,0.000000,0.189525,0.366414,0.457150,0.611141,0.048488,0.061898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USER_09996,0.342196,0.595880,0.258046,0.451335,0.366414,0.791353,0.166667,0.220113,0.265747,0.323942,...,0.000000,0.080064,0.088561,0.000000,0.222222,1.000000,0.000000,0.184053,0.071067,0.226805
USER_09997,0.330875,0.205331,0.000000,0.432991,0.457150,0.292165,0.000000,0.053093,0.464729,0.206835,...,0.000000,0.289683,0.267023,0.446134,0.150756,0.000000,1.000000,0.577137,0.000000,0.102576
USER_09998,0.250191,0.225613,0.000000,0.280926,0.611141,0.331726,0.368105,0.320857,0.234775,0.151511,...,0.238858,0.565862,0.195600,0.153789,0.184053,0.184053,0.577137,1.000000,0.251137,0.060111
USER_09999,0.105661,0.254084,0.025392,0.279927,0.048488,0.000000,0.355335,0.544367,0.113315,0.511891,...,0.368914,0.034139,0.377627,0.000000,0.000000,0.071067,0.000000,0.251137,1.000000,0.348155
USER_10000,0.072259,0.000000,0.243108,0.603023,0.061898,0.276916,0.204124,0.269582,0.000000,0.396746,...,0.264906,0.000000,0.596559,0.106600,0.680414,0.226805,0.102576,0.060111,0.348155,1.000000

##### Finding Similar products

In [52]:
item_name = user_item.columns

In [53]:
item_name

Index(['IT_01', 'IT_02', 'IT_03', 'IT_04', 'IT_05', 'IT_06', 'IT_07', 'IT_08',
       'IT_09', 'IT_10', 'IT_11', 'IT_12', 'IT_13', 'IT_14', 'IT_15'],
      dtype='object', name='item')

In [54]:
item_sim_df = 1 - pairwise_distances(item_user,metric='cosine')

In [55]:
item_sim_df

array([[1.        , 0.18997003, 0.19951651, 0.21776956, 0.2771214 ,
        0.29227707, 0.24459464, 0.17809753, 0.2179207 , 0.21473346,
        0.24414075, 0.19434825, 0.25901276, 0.26592383, 0.20774678],
       [0.18997003, 1.        , 0.18331083, 0.20753604, 0.22676459,
        0.25582443, 0.22549436, 0.15602411, 0.20292994, 0.20915401,
        0.19558886, 0.19406244, 0.21557776, 0.22252446, 0.18234529],
       [0.19951651, 0.18331083, 1.        , 0.22519965, 0.25753274,
        0.27329311, 0.24186942, 0.18324695, 0.21423098, 0.21051766,
        0.22302851, 0.20770825, 0.25772548, 0.25782093, 0.19155661],
       [0.21776956, 0.20753604, 0.22519965, 1.        , 0.29271845,
        0.31273709, 0.26494929, 0.1950769 , 0.23791582, 0.23098819,
        0.2527947 , 0.22891497, 0.28459986, 0.30549424, 0.2110109 ],
       [0.2771214 , 0.22676459, 0.25753274, 0.29271845, 1.        ,
        0.36674292, 0.28678444, 0.21847769, 0.27584965, 0.26516528,
        0.28886334, 0.24926901, 0.33764613, 0.33694886, 0.25275459],
       [0.29227707, 0.25582443, 0.27329311, 0.31273709, 0.36674292,
        1.        , 0.35159334, 0.23098079, 0.28892335, 0.30398902,
        0.31200217, 0.28726097, 0.3873479 , 0.38964239, 0.27568273],
       [0.24459464, 0.22549436, 0.24186942, 0.26494929, 0.28678444,
        0.35159334, 1.        , 0.1926905 , 0.2500125 , 0.26481482,
        0.2552384 , 0.24018204, 0.30850402, 0.30743179, 0.22696954],
       [0.17809753, 0.15602411, 0.18324695, 0.1950769 , 0.21847769,
        0.23098079, 0.1926905 , 1.        , 0.17619781, 0.19885146,
        0.18168658, 0.18543453, 0.21886324, 0.22311548, 0.16516413],
       [0.2179207 , 0.20292994, 0.21423098, 0.23791582, 0.27584965,
        0.28892335, 0.2500125 , 0.17619781, 1.        , 0.23831844,
        0.23603961, 0.23587233, 0.2703427 , 0.27069398, 0.22394503],
       [0.21473346, 0.20915401, 0.21051766, 0.23098819, 0.26516528,
        0.30398902, 0.26481482, 0.19885146, 0.23831844, 1.        ,
        0.24135761, 0.22484648, 0.28028971, 0.25740707, 0.22218784],
       [0.24414075, 0.19558886, 0.22302851, 0.2527947 , 0.28886334,
        0.31200217, 0.2552384 , 0.18168658, 0.23603961, 0.24135761,
        1.        , 0.23764727, 0.28807923, 0.28856421, 0.22588248],
       [0.19434825, 0.19406244, 0.20770825, 0.22891497, 0.24926901,
        0.28726097, 0.24018204, 0.18543453, 0.23587233, 0.22484648,
        0.23764727, 1.        , 0.25925763, 0.25384951, 0.2178331 ],
       [0.25901276, 0.21557776, 0.25772548, 0.28459986, 0.33764613,
        0.3873479 , 0.30850402, 0.21886324, 0.2703427 , 0.28028971,
        0.28807923, 0.25925763, 1.        , 0.35336914, 0.27920486],
       [0.26592383, 0.22252446, 0.25782093, 0.30549424, 0.33694886,
        0.38964239, 0.30743179, 0.22311548, 0.27069398, 0.25740707,
        0.28856421, 0.25384951, 0.35336914, 1.        , 0.27492302],
       [0.20774678, 0.18234529, 0.19155661, 0.2110109 , 0.25275459,
        0.27568273, 0.22696954, 0.16516413, 0.22394503, 0.22218784,
        0.22588248, 0.2178331 , 0.27920486, 0.27492302, 1.        ]])

In [56]:
item_sim_df = pd.DataFrame(item_sim_df, columns=item_name,index=item_name)

In [57]:
item_sim_df

item,IT_01,IT_02,IT_03,IT_04,IT_05,IT_06,IT_07,IT_08,IT_09,IT_10,IT_11,IT_12,IT_13,IT_14,IT_15
item,,,,,,,,,,,,,,,
IT_01,1.000000,0.189970,0.199517,0.217770,0.277121,0.292277,0.244595,0.178098,0.217921,0.214733,0.244141,0.194348,0.259013,0.265924,0.207747
IT_02,0.189970,1.000000,0.183311,0.207536,0.226765,0.255824,0.225494,0.156024,0.202930,0.209154,0.195589,0.194062,0.215578,0.222524,0.182345
IT_03,0.199517,0.183311,1.000000,0.225200,0.257533,0.273293,0.241869,0.183247,0.214231,0.210518,0.223029,0.207708,0.257725,0.257821,0.191557
IT_04,0.217770,0.207536,0.225200,1.000000,0.292718,0.312737,0.264949,0.195077,0.237916,0.230988,0.252795,0.228915,0.284600,0.305494,0.211011
IT_05,0.277121,0.226765,0.257533,0.292718,1.000000,0.366743,0.286784,0.218478,0.275850,0.265165,0.288863,0.249269,0.337646,0.336949,0.252755
IT_06,0.292277,0.255824,0.273293,0.312737,0.366743,1.000000,0.351593,0.230981,0.288923,0.303989,0.312002,0.287261,0.387348,0.389642,0.275683
IT_07,0.244595,0.225494,0.241869,0.264949,0.286784,0.351593,1.000000,0.192691,0.250012,0.264815,0.255238,0.240182,0.308504,0.307432,0.226970
IT_08,0.178098,0.156024,0.183247,0.195077,0.218478,0.230981,0.192691,1.000000,0.176198,0.198851,0.181687,0.185435,0.218863,0.223115,0.165164
IT_09,0.217921,0.202930,0.214231,0.237916,0.275850,0.288923,0.250012,0.176198,1.000000,0.238318,0.236040,0.235872,0.270343,0.270694,0.223945
IT_10,0.214733,0.209154,0.210518,0.230988,0.265165,0.303989,0.264815,0.198851,0.238318,1.000000,0.241358,0.224846,0.280290,0.257407,0.222188
IT_11,0.244141,0.195589,0.223029,0.252795,0.288863,0.312002,0.255238,0.181687,0.236040,0.241358,1.000000,0.237647,0.288079,0.288564,0.225882
IT_12,0.194348,0.194062,0.207708,0.228915,0.249269,0.287261,0.240182,0.185435,0.235872,0.224846,0.237647,1.000000,0.259258,0.253850,0.217833
IT_13,0.259013,0.215578,0.257725,0.284600,0.337646,0.387348,0.308504,0.218863,0.270343,0.280290,0.288079,0.259258,1.000000,0.353369,0.279205
IT_14,0.265924,0.222524,0.257821,0.305494,0.336949,0.389642,0.307432,0.223115,0.270694,0.257407,0.288564,0.253850,0.353369,1.000000,0.274923
IT_15,0.207747,0.182345,0.191557,0.211011,0.252755,0.275683,0.226970,0.165164,0.223945,0.222188,0.225882,0.217833,0.279205,0.274923,1.000000

In [59]:
def get_similar_users( userid, topN = 5 ):
    users_df = pd.DataFrame()
    users_df['similarity'] = user_sim[userid]
    top_n = users_df.sort_values( ["similarity"], ascending = False )[1:topN+1]
    print( "Top 5" + " Similar users to: " + userid + " are", )
    return top_n

def get_similar_items( itemid, topN = 5 ):
    items_df = pd.DataFrame()
    items_df['similarity'] = item_sim_df[itemid]
    top_n = items_df.sort_values( ["similarity"], ascending = False )[1:topN+1]
    print( "Top 5 Similar items to: " + itemid + " are", )
    return top_n

In [60]:
get_similar_items( 'IT_01' )

Top 5 Similar items to: IT_01 are

       similarity
item
IT_06    0.292277
IT_05    0.277121
IT_14    0.265924
IT_13    0.259013
IT_07    0.244595

In [61]:
get_similar_users('USER_00010')

Top 5 Similar users to: USER_00010 are

            similarity
user
USER_05860    0.984599
USER_01847    0.984092
USER_00133    0.980392
USER_09273    0.973026
USER_08418    0.970431